# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee038b2d7a15bfc2dfaafadff4fd9c310bf4a1b538fda6a9388e9403e5d90f1392b7d8a87e1121363eb34d70a264ed9b73da4df904f39ac0385aad0af367a2e0

test:
  secret_key_base: 41b491d51d13d35b8704952e49123d500e02212f5145c9106a5307d5288e36660c4f4f350302fea51bafef3bd5de91ddc53c740b9f80dd557e2b638f0410a68c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
